name: The Atlantis Light
favicon: null
layout_spectrum: 0.7770033746492118
typography_spectrum: 0.3325761496089399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1dc3db'
    - '#f7feff'
    - '#c8d2dc'
    - '#00274a'
    - '#7c858f'
  brandStrength: 0.5
  lightness: 0.7000576935242862
  saturation: 0.6875
  rhythmicContrast: 0.7377834529615939
purpose: []
